# Generated by Django 6.0.7 on 2026-08-01 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('district', models.CharField(blank=True, help_text='Biriktirilgan hudud', max_length=64)),
                ('avatar_initials', models.CharField(blank=True, max_length=4)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3)),
                ('tier', models.CharField(choices=[('Yangi', 'Yangi agent'), ('Faol', 'Faol makler'), ('Tajribali', 'Tajribali makler'), ('Top', 'Top Makler')], default='Yangi', max_length=16)),
                ('certification', models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Kutilmoqda', max_length=20)),
                ('platform_share', models.PositiveSmallIntegerField(default=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('avg_response_minutes', models.PositiveIntegerField(default=0)),
                ('total_deals', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-rating', '-total_deals'],
            },
        ),
    ]
