# Generated by Django 6.0.7 on 2026-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='historical_deals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
